// Microgreens seed data from yield analysis
export const microgreensData = [
  {
    sku: "MIC-001",
    name: "Amaranth (Red)",
    variety: "Red",
    seedCode: "TLF-ST-AMA-RED",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-002",
    name: "Barley",
    variety: "Standard",
    seedCode: "TLF-ST-BAR",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-003",
    name: "Basil (Dark Opal)",
    variety: "Dark Opal",
    seedCode: "TLF-ST-BAS-DOP",
    growTime: 12,
    yieldPerTray: 90,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-004",
    name: "Basil (Green)",
    variety: "Green",
    seedCode: "TLF-ST-BAS-GRE",
    growTime: 12,
    yieldPerTray: 115,
    seedingDensity: 20,
    defaultSeedCostPerGram: 11.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-005",
    name: "Basil (Lemon)",
    variety: "Lemon",
    seedCode: "TLF-ST-BAS-LEM",
    growTime: 12,
    yieldPerTray: 115,
    seedingDensity: 20,
    defaultSeedCostPerGram: 11.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-006",
    name: "Basil (Red Rubin)",
    variety: "Red Rubin",
    seedCode: "TLF-ST-BAS-RED",
    growTime: 12,
    yieldPerTray: 115,
    seedingDensity: 20,
    defaultSeedCostPerGram: 11.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-007",
    name: "Beetroot (Bulls Blood)",
    variety: "Bulls Blood",
    seedCode: "TLF-ST-BEE-BBL",
    growTime: 10,
    yieldPerTray: 130,
    seedingDensity: 20,
    defaultSeedCostPerGram: 2.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-008",
    name: "Beetroot (Detroit Dark Red)",
    variety: "Detroit Dark Red",
    seedCode: "TLF-ST-BEE-DET",
    growTime: 10,
    yieldPerTray: 90,
    seedingDensity: 20,
    defaultSeedCostPerGram: 2.56,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-009",
    name: "Bunching Onion (Apache)",
    variety: "Apache",
    seedCode: "TLF-ST-BON-APA",
    growTime: 14,
    yieldPerTray: 90,
    seedingDensity: 15,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-010",
    name: "Bunching Onion (Natsuyo/NO.1)",
    variety: "Natsuyo",
    seedCode: "TLF-ST-BON-NAT",
    growTime: 14,
    yieldPerTray: 115,
    seedingDensity: 15,
    defaultSeedCostPerGram: 8.33,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-011",
    name: "Borage",
    variety: "Standard",
    seedCode: "TLF-ST-BOR",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 4.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-012",
    name: "Broccoli",
    variety: "Standard",
    seedCode: "TLF-ST-BRO",
    growTime: 8,
    yieldPerTray: 100,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.55,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-013",
    name: "Cabbage (Chinese)",
    variety: "Chinese",
    seedCode: "TLF-ST-CAB-C",
    growTime: 10,
    yieldPerTray: 90,
    seedingDensity: 20,
    defaultSeedCostPerGram: 5.84,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-014",
    name: "Cabbage (Red)",
    variety: "Red",
    seedCode: "TLF-ST-CAB-R",
    growTime: 10,
    yieldPerTray: 115,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.85,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-015",
    name: "Carrot (Amsterdam)",
    variety: "Amsterdam",
    seedCode: "TLF-ST-CAR-AMS",
    growTime: 12,
    yieldPerTray: 100,
    seedingDensity: 20,
    defaultSeedCostPerGram: 5.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-016",
    name: "Carrot (Nantes)",
    variety: "Nantes",
    seedCode: "TLF-ST-CAR-NAN",
    growTime: 12,
    yieldPerTray: 100,
    seedingDensity: 20,
    defaultSeedCostPerGram: 4.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-017",
    name: "Celery (Egnazia Dark Green)",
    variety: "Egnazia Dark Green",
    seedCode: "TLF-ST-CEL",
    growTime: 14,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 7.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-018",
    name: "Swiss Chard (Green Stem)",
    variety: "Green Stem",
    seedCode: "TLF-ST-CHA-G",
    growTime: 10,
    yieldPerTray: 120,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.57,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-019",
    name: "Swiss Chard (Red Stem)",
    variety: "Red Stem",
    seedCode: "TLF-ST-CHA-R",
    growTime: 10,
    yieldPerTray: 120,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.17,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-020",
    name: "Swiss Chard (Rainbow)",
    variety: "Rainbow",
    seedCode: "TLF-ST-CHA-RB",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.83,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-021",
    name: "Swiss Chard (White Stem)",
    variety: "White Stem",
    seedCode: "TLF-ST-CHA-W",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.83,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-022",
    name: "Swiss Chard (Yellow Stem)",
    variety: "Yellow Stem",
    seedCode: "TLF-ST-CHA-Y",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.83,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-023",
    name: "Chives (Garlic - Shiva)",
    variety: "Garlic",
    seedCode: "TLF-ST-CHI-GAR",
    growTime: 14,
    yieldPerTray: 100,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.75,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-024",
    name: "Chives (Prago - Imported)",
    variety: "Prago",
    seedCode: "TLF-ST-CHI-PRA",
    growTime: 14,
    yieldPerTray: 100,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.75,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-025",
    name: "Chia",
    variety: "Standard",
    seedCode: "TLF-ST-CHIA",
    growTime: 8,
    yieldPerTray: 120,
    seedingDensity: 15,
    defaultSeedCostPerGram: 8.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-026",
    name: "Red Clover",
    variety: "Red",
    seedCode: "TLF-ST-CLO-RED",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 15,
    defaultSeedCostPerGram: 6.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-027",
    name: "Coriander (Moroccan)",
    variety: "Moroccan",
    seedCode: "TLF-ST-COR-MOR",
    growTime: 10,
    yieldPerTray: 90,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-028",
    name: "Coriander (Santorini)",
    variety: "Santorini",
    seedCode: "TLF-ST-COR-SAN",
    growTime: 10,
    yieldPerTray: 90,
    seedingDensity: 20,
    defaultSeedCostPerGram: 3.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-029",
    name: "Cress",
    variety: "Standard",
    seedCode: "TLF-ST-CRE",
    growTime: 8,
    yieldPerTray: 100,
    seedingDensity: 20,
    defaultSeedCostPerGram: 1.96,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-030",
    name: "Cress (Red Daikon Radish)",
    variety: "Red Daikon",
    seedCode: "TLF-ST-CRE-RED",
    growTime: 8,
    yieldPerTray: 100,
    seedingDensity: 20,
    defaultSeedCostPerGram: 8.33,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-031",
    name: "Dill (Common)",
    variety: "Common",
    seedCode: "TLF-ST-DIL-COM",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 7.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
];

// Additional varieties from the PDF (page 2)
export const additionalMicrogreens = [
  {
    sku: "MIC-032",
    name: "Dill (Dukat)",
    variety: "Dukat",
    seedCode: "TLF-ST-DIL-DUK",
    growTime: 10,
    yieldPerTray: 120,
    seedingDensity: 20,
    defaultSeedCostPerGram: 7.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-033",
    name: "Fennel (Sweet Florence)",
    variety: "Sweet Florence",
    seedCode: "TLF-ST-FEN",
    growTime: 12,
    yieldPerTray: 136,
    seedingDensity: 20,
    defaultSeedCostPerGram: 7.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-034",
    name: "Kale (Choumollier)",
    variety: "Choumollier",
    seedCode: "TLF-ST-KAL-CHO",
    growTime: 10,
    yieldPerTray: 120,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-035",
    name: "Kale (Dark Green)",
    variety: "Dark Green",
    seedCode: "TLF-ST-KAL-DGR",
    growTime: 10,
    yieldPerTray: 115,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.80,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-036",
    name: "Kale (Green Curly)",
    variety: "Green Curly",
    seedCode: "TLF-ST-KAL-GRC",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-037",
    name: "Kale (Red Russian)",
    variety: "Red Russian",
    seedCode: "TLF-ST-KAL-RER",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 5.75,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-038",
    name: "Kohlrabi (Purple)",
    variety: "Purple",
    seedCode: "TLF-ST-KOH-PUR",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 10.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-039",
    name: "Kohlrabi (White)",
    variety: "White",
    seedCode: "TLF-ST-KOH-WHI",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 10.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-040",
    name: "Lettuce (Imperiale/Regina)",
    variety: "Imperiale",
    seedCode: "TLF-ST-LET-IMP",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-041",
    name: "Lettuce (Irma)",
    variety: "Irma",
    seedCode: "TLF-ST-LET-IRM",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-042",
    name: "Lettuce (Marina/Linfa)",
    variety: "Marina",
    seedCode: "TLF-ST-LET-LIN",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-043",
    name: "Lettuce (Lollo Bionde)",
    variety: "Lollo Bionde",
    seedCode: "TLF-ST-LET-LOL",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-044",
    name: "Lettuce (Marilisa)",
    variety: "Marilisa",
    seedCode: "TLF-ST-LET-MAR",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-045",
    name: "Lettuce (New York/Giglio)",
    variety: "New York",
    seedCode: "TLF-ST-LET-NEW",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-046",
    name: "Lettuce (Red Oakleaf)",
    variety: "Red Oakleaf",
    seedCode: "TLF-ST-LET-RED",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-047",
    name: "Lettuce (Marsala)",
    variety: "Marsala",
    seedCode: "TLF-ST-LET-SAL",
    growTime: 10,
    yieldPerTray: 180,
    seedingDensity: 20,
    defaultSeedCostPerGram: 9.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-048",
    name: "Lettuce (Sara/Savoir)",
    variety: "Sara",
    seedCode: "TLF-ST-LET-SAR",
    growTime: 10,
    yieldPerTray: 150,
    seedingDensity: 20,
    defaultSeedCostPerGram: 7.50,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-049",
    name: "Lettuce (Smeraldo/Demetra)",
    variety: "Smeraldo",
    seedCode: "TLF-ST-LET-SME",
    growTime: 10,
    yieldPerTray: 120,
    seedingDensity: 20,
    defaultSeedCostPerGram: 6.00,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
  {
    sku: "MIC-050",
    name: "Lettuce (Sublime)",
    variety: "Sublime",
    seedCode: "TLF-ST-LET-SUB",
    growTime: 10,
    yieldPerTray: 119,
    seedingDensity: 20,
    defaultSeedCostPerGram: 5.95,
    defaultSoilCostPerTray: 1.25,
    defaultTrayCost: 0.50,
    isActive: true,
  },
];

// Combine all microgreens
export const allMicrogreens = [...microgreensData, ...additionalMicrogreens];
